import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_slidable/flutter_slidable.dart';
import 'package:intl/intl.dart';
import 'package:nota/bloc/bloc.dart';
import 'package:nota/database/database.dart';
import 'package:nota/models/models.dart';
import 'package:nota/shared/shared.dart';
import 'package:nota/ui/component/list_item/list_item.dart';
import 'package:nota/ui/component/modal/modal.dart';
import 'package:nota/ui/widget/widget.dart';

part 'wrapper.dart';
part 'splash_page.dart';
part 'main_page.dart';
part 'dashboard_page.dart';
part 'stock_page.dart';
part 'company_page.dart';
part 'transaction_page.dart';
// part 'note_page.dart';
// part 'form_stock_page.dart';
// part 'form_company_page.dart';
// part 'form_transaction_page.dart';
